[package]
name = "veritas"
version = "0.5.0"
edition = "2024_07"

[dependencies]
starknet = "2.16.0"

[[target.starknet-contract]]

[dev-dependencies]
snforge_std = "0.57.0"

[tool.fmt]
sort-module-level-items = true

[tool.snforge]
exit_first = true
